autoDetectedPackages:
- algo.base.ch001
- algo.base.ch002
- algo.base.ch003
- algo.base.ch04
- ch11
- ch31
- com.anotation
- com.classloader
- com.collection
- com.exception
- com.fanshe
- com.fanxing
- com.jia.aqs
- com.jia.atomic
- com.jia.blckingqueue
- com.jia.collection
- com.jia.disruptor
- com.jia.dp
- com.jia.future
- com.jia.interrupt
- com.jia.lock
- com.jia.support
- com.jia.suspension
- com.jia.syn
- com.jia.threadlocal
- com.jia.threadpool
- com.jia.threadstatus
- com.minispring
- com.ncst.bio
- com.ncst.dp
- com.ncst.netty.buf
- com.ncst.netty.codec
- com.ncst.netty.groupchat
- com.ncst.netty.hearbeat
- com.ncst.netty.http
- com.ncst.netty.inboundhandlerandoutboundhandler
- com.ncst.netty.protocoltcp
- com.ncst.netty.simple
- com.ncst.netty.source.echo
- com.ncst.netty.tcp
- com.ncst.netty.websocket
- com.ncst.nettyaction
- com.ncst.nio
- com.ncst.rpc.consumer
- com.ncst.rpc.netty
- com.ncst.rpc.provider
- com.ncst.rpc.publicinterface
- com.proxy
- com.qxlx
- com.spi
- demo.test
- design
- ehcache
- entity
- jvmtool
- mapper
- oom
- wz001
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
