server:
  port: 8088

#数据源连接信息
spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      register-mbeans: true
      maximum-pool-size: 150
      minimum-idle: 25
  application:
    name: api-test #设置当前应用名称，在eureka中Aoolication显示，通过该名称可以获取路径
#  cloud:
#    nacos:
#      server-addr: http://localhost:8848 # nacos服务地址